# Generated by Django 5.1.15 on 2026-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="done_requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="Only a lead, manager or admin may move a task to Done",
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="workflow_transitions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="done_requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="Only a lead, manager or admin may move a task to Done",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="workflow_transitions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
